command: ["/bin/bash", "startup.sh"]
# databricks apps listen by default on port 8000
runtime: nodejs20

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: CHAT_APP_PORT
    value: "3000"
  - name: API_PROXY
    value: "http://localhost:8000/invocations"
  - name: MLFLOW_EXPERIMENT_ID
    value: "1021971371025173" # fill in with your experiment ID
  - name: DATABRICKS_SERVING_ENDPOINT # remove soon
    value: "databricks-gpt-oss-120b" # FMAPI

